from views.WelcomeView import WelcomeView
from views.RoleChooseView import RoleChooseView
from views.VerificationView import VerificationView
from views.RoleSubmitButtonView import RoleSubmitButtonView
