from views.WelcomeView import WelcomeView
from views.RoleChooseView import RoleChooseView
from views.VerificationView import VerificationView
from views.components.DoneButtonView import DoneButtonView