from views.WelcomeView import WelcomeView
from views.PronounsView import PronounsView
from views.PrononsView import PrononsView
from views.GenreChooseView import GenreChooseView
from views.GenreChoose2View import GenreChoose2View
from views.GenreChooseV2View import GenreChooseV2View
from views.GenreChooseV3View import GenreChooseV3View
from views.LastMSGView import LastMSGView
from views.LastMSGV2View import LastMSGV2View
from views.VerificationView import VerificationView
from views.components.DoneButtonView import DoneButtonView